# Generated by Django 3.0.8 on 2020-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/about_thumbnail/')),
                ('about_content', models.CharField(max_length=1000)),
                ('about_image', models.FileField(blank=True, null=True, upload_to='static/about_image/')),
                ('faculty_content', models.CharField(max_length=1000)),
                ('partner_image1', models.FileField(blank=True, null=True, upload_to='static/partner_image/')),
                ('partner_image2', models.FileField(blank=True, null=True, upload_to='static/partner_image/')),
                ('partner_image3', models.FileField(blank=True, null=True, upload_to='static/partner_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/contact_thumbnail/')),
                ('telephone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_text', models.CharField(max_length=80)),
                ('event_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_member_number', models.CharField(max_length=5)),
                ('faculty_member_footer', models.CharField(max_length=200)),
                ('robotics_center_info_title', models.CharField(max_length=30)),
                ('robotics_center_info_about', models.CharField(max_length=200)),
                ('students_number', models.CharField(max_length=5)),
                ('students_number_footer', models.CharField(max_length=200)),
                ('department_title', models.CharField(max_length=30)),
                ('department_info_under_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='head_thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('second_row', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/main_thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/news_thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=80)),
                ('project_image', models.FileField(blank=True, null=True, upload_to='static/project_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=50)),
                ('research_content', models.CharField(max_length=350)),
                ('research_image', models.FileField(blank=True, null=True, upload_to='static/research_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Research_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('second_row', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/research_thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('second_row', models.CharField(blank=True, max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/vision_thumbnail/')),
                ('goal_title_1', models.CharField(max_length=50)),
                ('goal_content_1', models.CharField(blank=True, max_length=250)),
                ('goal_image_1', models.FileField(blank=True, null=True, upload_to='static/vision_image/')),
                ('goal_title_2', models.CharField(max_length=50)),
                ('goal_content_2', models.CharField(blank=True, max_length=250)),
                ('goal_image_2', models.FileField(blank=True, null=True, upload_to='static/vision_image/')),
                ('goal_title_3', models.CharField(max_length=50)),
                ('goal_content_3', models.CharField(blank=True, max_length=250)),
                ('goal_image_3', models.FileField(blank=True, null=True, upload_to='static/vision_image/')),
            ],
        ),
    ]
