# Generated by Django 2.1 on 2020-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_text', models.CharField(max_length=80)),
                ('event_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_member_number', models.CharField(max_length=5)),
                ('faculty_member_footer', models.CharField(max_length=80)),
                ('robotics_center_info_title', models.CharField(max_length=30)),
                ('robotics_center_info_about', models.CharField(max_length=80)),
                ('students_number', models.CharField(max_length=5)),
                ('students_number_footer', models.CharField(max_length=80)),
                ('department_title', models.CharField(max_length=30)),
                ('department_info_under_title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='head_thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('second_row', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/main_thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=80)),
                ('project_image', models.FileField(blank=True, null=True, upload_to='static/project_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=50)),
                ('research_content', models.CharField(max_length=150)),
                ('research_image', models.FileField(blank=True, null=True, upload_to='static/research_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Research_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_statement', models.CharField(max_length=60)),
                ('second_row', models.CharField(max_length=60)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='static/research_thumbnail/')),
            ],
        ),
    ]
