# Generated by Django 3.0.8 on 2020-11-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_image',
            field=models.FileField(blank=True, null=True, upload_to='static/contact_image/'),
        ),
    ]
