# Generated by Django 3.0.8 on 2020-11-09 20:46

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('robotxapp', '0004_auto_20201109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='faculty_content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='partner_image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
