# Generated by Django 3.0.8 on 2020-11-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotxapp', '0006_auto_20201110_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department_info_under_title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_member_footer',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='robotics_center_info_about',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='students_number_footer',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_content',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='vision',
            name='goal_content_1',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='vision',
            name='goal_content_2',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='vision',
            name='goal_content_3',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
